getgenv().UrbanKey == ""
if UrbanKey == "" then
    if game.GameId == 3471372453 then -- Find The Anime
        loadstring(game:HttpGet(('https://raw.githubusercontent.com/Urbanstorms/UrbanHub/main/Find%20The%20Anime.Lua'),true))()
    elseif game.GameId == 0 then
        --Loadstring
    elseif game.GameId == 0 then
        --Loadstring
    elseif game.GameId == 0 then
        --Loadstring
    elseif game.GameId == 0 then
        --Loadstring
    elseif game.GameId == 0 then
        --Loadstring
    elseif game.GameId == 0 then
        --Loadstring
    elseif game.GameId == 0 then
        --Loadstring
    
    end
end
